projects:
  analogueArch:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        graphQLApiId: prjqewd6nrbhvfh7xixttb25fe
      endpoints:
        prod: >-
          https://5ngmpjsqera5ljdtyjtye4k2a4.appsync-api.eu-west-1.amazonaws.com/graphql
